### ISSUE TITLE
Semicolons in preview

### ISSUE THREAD

**Issue by tlevine** [csvsoundsystem/federal-treasury-api#151]
As an obsessive SQL programmer,
I want to be able to write a line-ending semicolon when previewing my query
so that I can write ordinary SQL.

This currently is broken because `limit 10` is added when you preview something. We could do something like this

1. Remove the trailing semicolon if it exists.
2. Check for "limit", case-insensitive, and add limit 10 if a limit does not exist.

**Comment by mhkeller** [comment]
Gonna close this for now since it works for most users
