### ISSUE TITLE
Screencast about the post-merge hook

### ISSUE THREAD

**Issue by tlevine** [csvsoundsystem/federal-treasury-api#177]
As CSV, I want a screencast about how the post-merge hook works and why we don't need to commit `table_schema.json`.

I think nobody understands this right now.

**Comment by mhkeller** [comment]
#182 is closed and @bdewilde is curious about the post merge hook. Do you still remember this one @tlevine

**Comment by tlevine** [comment]
Oh, actually, I am free now. I was off by a week. Open this, or I can
call you.
https://chatb.org/#KPPVLTDJLNVGXC

Michael Keller writes:

**Comment by tlevine** [comment]
I didn't remember, but I checked the documentation. According to the
readme, we should set up the git post-merge hook in utils/post-merge.
This hook generates the table_schema.json.

Michael Keller writes:

**Comment by mhkeller** [comment]
@tlevine  we're in the chatb room

**Comment by mhkeller** [comment]
The things in run.sh are run after the repo is pulled from github
