### ISSUE TITLE
Make queries use CloudFront

### ISSUE THREAD

**Issue by tlevine** [csvsoundsystem/federal-treasury-api#190]
Queries in all of the libraries and websites should use api.treasury.io rather than premium.scraperwiki.com so that queries are fast and get logged.

**Comment by mhkeller** [comment]
@bdewilde can do the python one. I'll do the Node one and the R one. @tlevine can you do the Ruby one and update it on whatever registry that uses, if that is how it's set up to work.

**Comment by bdewilde** [comment]
@tlevine : looks like you'll have to push the change to pypi

```
pytreasuryio(master*)$ twine upload dist/treasuryio-0.0.4*
Uploading distributions to https://pypi.python.org/pypi
Enter your password:
Uploading treasuryio-0.0.4-py2-none-any.whl
[================================] 13432/13432 - 00:00:00
HTTPError: 403 Client Error: You are not allowed to edit 'treasuryio' package information for url: https://pypi.python.org/pypi
```

**Comment by bdewilde** [comment]
`pytreasuryio` updated on pypi: https://pypi.python.org/pypi/treasuryio
