### ISSUE TITLE
+/- buttons on Query Builder are unclear

### ISSUE THREAD

**Issue by abelsonlive** [csvsoundsystem/federal-treasury-api#82]
It makes it seem like you should click them to increment values up and down.  Maybe make them say "Add Condition" or "Remove Condition"

Also, is this supposed to seem _less_ confusing than writing vanilla SQL?

![screen shot 2013-06-29 at 1 48 09 pm](https://f.cloud.github.com/assets/1621721/726272/3be6e1b6-e0e4-11e2-8984-96e5ed4a18b6.png)

**Comment by mhkeller** [comment]
This is related to the old query builder
